### Config

# options
set -sg escape-time 0
set -g renumber-windows on
set -g mouse on
set -g repeat-time 1000
set -g history-limit 10000
set -g status-interval 2

# set colour definitions
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-kitty:RGB"

# status bar styling
set -g status-style bg=color10 
set -g status-justify absolute-centre
set -g status-left-length 100
set -g status-left "#{W: #{?window_active,#[fg=color231],#{?window_last_flag,#[fg=color250],#[fg=color244]}}#I:#W#{?window_flags,#{window_flags},} }#[default]"
set -g status-right-length 100
set -g status-right "#[fg=color237,bg=default]#(tmux-mem-cpu-load --interval 2)#[default]"
set -g window-status-current-format "#[fg=color225,bright] #S #[default]"
set -g window-status-format "" 

# pane styling
set -g pane-border-lines simple
set -g pane-border-style fg=color117
set -g pane-active-border-style fg=color195

# prefix changed from (ctr + b)
set -g prefix `
bind ` send-prefix

# base indexing
set -g base-index 1
set -g pane-base-index 1


### Keybindings

bind -n C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch -client -t \$name"'

bind -n C-s display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# vim to hyprland.conf
bind -n C-h display-popup \
  -w 80% \
  -h 80% \
  -E 'vim ~/.config/hypr/hyprland.conf'

# run lazygit
bind -n C-z display-popup \
  -w 80% \
  -h 80% \
  -d "#{pane_current_path}" \
  -E "lazygit"
 
# execute zsh terminal
bind -n C-t display-popup \
  -d "#{pane_current_path}" \
  -E "zsh"

bind r source-file ~/.tmux.conf \; display-message "Reloading tmux Config >.>"

run-shell ~/.config/tmux/plugins/sidebar.tmux
