-- ------------------------------------------------------------------------------------
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- ------------------------------------------------------------------------------------

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf


-- -----------------------------------
-- ------ ENVIRONMENT VARIABLES ------
-- -----------------------------------

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("HYPRCURSOR_THEME", "theme_minecraft-hypr")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "minecraft-theme") -- Keep as fallback for GTK apps
hl.env("XCURSOR_SIZE", "24")

-- Nvidia drivers
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
-- hl.env("__GL_GSYNC_ALLOWED", "0")
-- hl.env("__GL_VRR_ALLOWED", "0")
hl.env("GBM_BACKEND", "nvidia-drm")

-- Additional
hl.env("MANGOHUD_CONFIGFILE", "$HOME/.config/MangoHud/MangoHud.conf")


-- ----------------------
-- ------ MONITORS ------
-- ----------------------

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({
  output = "",
  mode = "highrr",
  position = "auto",
  scale = "auto",
})


-- -------------------------
-- ------ MY PROGRAMS ------
-- -------------------------

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
local terminal = "kitty bash"
local fileManager = "dolphin"
local menu = "wofi --show=drun"
local browser = "chromium"


-- -----------------------
-- ------ AUTOSTART ------
-- -----------------------

hl.on("hyprland.start", function()
  -- System
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")

  -- Programs 
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("pasystray")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("swaync")
  hl.exec_cmd("swaync-client -df")
  hl.exec_cmd("swayosd-server -s ~/.config/swayosd/style.css")
  hl.exec_cmd("otd-daemon")
  hl.exec_cmd("sleep 1 && waybar")
  hl.exec_cmd("sleep 1 && spotify-launcher &")
end)


-- -------------------------
-- ------ EXEC RELOAD ------
-- -------------------------

-- Once reloading config these settings execute/set/apply
hl.exec_cmd("wal -s -t -i ~/wallpapers/pywallpaper.jpg && pkill -SIGUSR2 waybar")


-- -------------------------
-- ------ PERMISSIONS ------
-- -------------------------

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem {
--     enforce_permissions = true
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-- ---------------------------
-- ------ LOOK AND FEEL ------
-- ---------------------------

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/--general
hl.config({
  general = {
      gaps_in = 5,
      gaps_out = 10,

      border_size = 2,

      -- https://wiki.hypr.land/Configuring/Variables/--variable-types for info about colors
      col = {
            active_border   = { colors = {"rgba(ffffffee)", "rgba(ffe5eaee)"}, angle = 45 },
            inactive_border = "rgba(636363ee)",
        },

      -- Set to true enable resizing windows by clicking and dragging on borders and gaps
      resize_on_border = false,

      -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
      allow_tearing = false,

      layout = "dwindle",
  },

  -- https://wiki.hypr.land/Configuring/Variables/--decoration
  decoration = {
      rounding = 0,
      rounding_power = 2,

      -- Change transparency of focused and unfocused windows
      active_opacity = 1.0,
      inactive_opacity = 1.0,
      fullscreen_opacity = 1.0,

      -- https://wiki.hypr.land/Configuring/Variables
      blur = {
	  enabled = true,
	  size = 8,                  -- bigger radius → softer blur (frosted glass)
	  passes = 4,                -- more passes → smoother blur
	  new_optimizations = true,  -- helps performance
	  contrast = 1.0,
	  brightness = 1.0,
	  noise = 0.015,             -- subtle grain prevents banding
	  vibrancy = 0.2, 
	  popups = true,
      },
      
      shadow = {
	  enabled = true,
	  range = 4,
	  render_power = 3,
	  color = "rgba(1F1D19ee)",
      },
  },

  -- https://wiki.hypr.land/Configuring/Variables/--animations
  animations = {
      enabled = true,
  },

  -- https://wiki.hypr.land/Configuring/XWayland/
  xwayland = {
      force_zero_scaling = true,
  },

  -- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
  dwindle = {
      preserve_split = true, -- You probably want this
  },

  -- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
  master = {
      new_status = "master",
  },

  -- https://wiki.hypr.land/Configuring/Variables/--misc
  misc = {
      force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
      disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background
      focus_on_activate = true,
  },
})


-- ------------------------
-- ------ Animations ------
-- ------------------------

-- Curves
hl.curve("curve", { type = "bezier", points = { {0, 1}, {0, 1} } })

-- Animations
hl.animation({ leaf = "windows",    enabled = true,  speed = 2, bezier = "curve",   style = "slide" })
hl.animation({ leaf = "border",     enabled = true,  speed = 5, bezier = "default" })
hl.animation({ leaf = "fade",       enabled = false, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true,  speed = 2, bezier = "curve",   style = "fade" })


-- ---------------------
-- ------ DEVICES ------
-- ---------------------

-- https://wiki.hypr.land/Configuring/Variables/--input

hl.config({  
    input = {
        kb_layout = "us,jp",
        kb_variant = "",
        kb_model = "",
        kb_options = "grp:win_space_toggle",
        kb_rules = "",

        follow_mouse = 1,

        sensitivity = -0.5, -- -1.0 - 1.0, 0 means no modification.
        accel_profile = "flat",

	tablet = {
	    transform = 0,
	    output = "",
	    region_position = "0 0",
	    region_size = "0 0",
	    relative_input = false,
	},

	touchpad = {
	    natural_scroll = true,
	},
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures
hl.gesture({
    fingers = 3, 
    direction = "horizontal", 
    action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Keywords/--per-device-input-configs for more
hl.device ({
    name = "epic-mouse-v1",
    sensitivity = 0,
})

hl.device ({
    name = "opentabletdriver-virtual-artist-tablet",
})


-- -------------------------
-- ------ KEYBINDINGS ------
-- -------------------------

-- See https://wiki.hypr.land/Configuring/Keywords/
-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Define osd for swayosd support (Lua string concatenation)
local osd = 'swayosd-client --monitor "$(hyprctl monitors -j | jq -r \'.[] | select(.focused == true).name\')"'

-- Basic Application Binds
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("kitty -e tmux new-session -A -s main"))
hl.bind(mainMod .. " + B", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())

-- Select scripts
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("~/.config/hypr/wallpaper.sh"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("~/.config/waybar/scripts/select.sh"))

-- Toggle scripts
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("~/.bash-scripts/tablet-control.sh"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Move window with alt + arrow keys
hl.bind(mainMod .. " + ALT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + ALT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + ALT + down",  hl.dsp.window.move({ direction = "down" }))

-- Move / resize windows with mainMod + mouse
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Screenshot keys
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m region -o ~/screenshots/"))
hl.bind("Print",        hl.dsp.exec_cmd("hyprshot -m window -o ~/screenshots/"))
hl.bind("ALT + Print",  hl.dsp.exec_cmd("hyprshot -m active -m output -o ~/screenshots/"))

-- Lockscreen
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- Workspaces 1-10 (Replaces 20 repetitive lines with 1 loop)
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Media & OSD keys (bindel -> locked + repeating)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(osd .. " --output-volume raise"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(osd .. " --output-volume lower"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd(osd .. " --brightness +10"),      { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(osd .. " --brightness -10"),      { locked = true, repeating = true })

-- Media keys (bindl -> locked)
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- ------------------------
-- ------ LAYERRULES ------
-- ------------------------

local waybarlayerrule = hl.layer_rule({
    name = "waybarrules",
    match = { namespace = "waybar" },
    ignore_alpha = 0.5,
    blur = true,
})
-- waybarlayerrule:set_enabled(true)

local swaycontrollayerrule = hl.layer_rule({
    name = "swaycontrolrules",
    match = { namespace = "swaync-control-center" },
    ignore_alpha = 0.5,
    blur = true,
})
swaycontrollayerrule:set_enabled(true)

local swaynotiflayerrule = hl.layer_rule({
    name = "swaynotifrules",
    match = { namespace = "swaync-notification-window" },
    ignore_alpha = 0.5,
    blur = true,
})
swaynotiflayerrule:set_enabled(true)

local swayosdlayerrule = hl.layer_rule({
    name = "swayosdrules",
    match = { namespace = "swayosd" },
    no_anim = true,
    blur = true,
})
swayosdlayerrule:set_enabled(true)

-- --------------------------
-- ------ WINDOW RULES ------
-- --------------------------

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- WORKSPACE RULES FOR PROGRAMS
hl.window_rule({
  name = "spotify-open",
  match = { class = "^Spotify$" },
  workspace = "10 silent",
})

hl.window_rule({
  name = "wireshark-open",
  match = { class = "^org\\.wireshark\\.Wireshark$" },
  float = true,
})

hl.window_rule({
  name = "floating-notes",
  match = { class = "^floating_notes$" },
  float = true,
  size = "1400 1000",
  center = true,
})

hl.window_rule({
  name = "global-no-maximize",
  match = { class = ".*" },
  suppress_event = "maximize",
})

hl.window_rule({
  name = "xwayland-compat",
  match = { xwayland = true },
  opaque = true,
})
